import {useState} from 'react';
import {Sparkles,ArrowUp,FileSearch,LoaderCircle} from 'lucide-react';
import {metricName} from '../services/labels';
export function AIResult({result,onEvidence}){
 if(!result)return null;
 return <article className="ai-result"><div className="ai-mode"><Sparkles size={16}/>{result.mode==='openai'?'ОТВЕТ ИИ · OPENAI':'СВОДКА ПО ПРАВИЛАМ'}</div><p className="muted small">{result.notice}</p>{result.summary&&<h3>{result.summary}</h3>}{result.priority_explanation&&<p>{result.priority_explanation}</p>}{result.answer&&<p className="preserve">{result.answer}</p>}{result.signals?.map(s=><div className="signal" key={s.name}><span>{metricName(s.name)}</span><b>{s.evidence}</b></div>)}{result.suggested_checks?.length>0&&<><h4>Что проверить дальше</h4><ul>{result.suggested_checks.map((s,i)=><li key={i}>{s}</li>)}</ul></>}<p className="limitations">{result.limitations}</p>{(result.evidence_node_ids||[undefined]).map((id,i)=><button key={id||i} onClick={()=>onEvidence(id)}><FileSearch size={16}/>Посмотреть основания{result.evidence_node_ids?.length>1?` · ${id}`:''}</button>)}</article>
}
export default function AICopilot({node,result,messages,onExplain,onAsk,onEvidence,busy}){
 const [question,setQuestion]=useState('');
 const submit=e=>{e.preventDefault();if(question.trim()){onAsk(question.trim());setQuestion('');}};
 return <div className="copilot"><div className="copilot-intro"><span className="copilot-icon"><Sparkles size={27}/></span><h3>Понятно о выбранном счёте</h3><p>Помогу разобраться, почему счёт выделен, с кем он связан и что стоит проверить.</p></div><button className="primary w-full" onClick={onExplain} disabled={busy||!node}>{busy?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>}Объяснить оценку {node?.node_id||'счёта'}</button>{busy&&<p className="ai-loading" role="status">Готовим объяснение по данным…</p>}<AIResult result={result} onEvidence={onEvidence}/>{messages.map((m,i)=><div key={i}><div className="question-bubble">{m.question}</div><AIResult result={m.result} onEvidence={onEvidence}/></div>)}<div className="quick-questions">{['Почему этот счёт выделен?','Куда уходят деньги дальше?'].map(q=><button disabled={busy||!node} key={q} onClick={()=>onAsk(q)}>{q}</button>)}</div><form className="chat-form" onSubmit={submit}><input aria-label="Вопрос ИИ-помощнику" value={question} maxLength={1000} onChange={e=>setQuestion(e.target.value)} placeholder="Ваш вопрос о счёте…" disabled={!node||busy}/><button className="primary" aria-label="Отправить вопрос" disabled={!node||busy||!question.trim()}><ArrowUp size={19}/></button></form><small className="muted">ИИ получает показатели и часть переводов выбранного счёта. Проверяйте ответ по исходным данным.</small></div>
}
