import {useState} from 'react';
import {Sparkles,ArrowUp,FileSearch,LoaderCircle} from 'lucide-react';
export function AIResult({result,onEvidence}){
 if(!result)return null;
 return <article className="ai-result"><div className="ai-mode"><Sparkles size={15}/>{result.mode==='openai'?'OPENAI COPILOT':'LOCAL EXPLANATION'}</div><p className="muted small">{result.notice}</p>{result.summary&&<h3>{result.summary}</h3>}{result.priority_explanation&&<p>{result.priority_explanation}</p>}{result.answer&&<p className="preserve">{result.answer}</p>}{result.signals?.map(s=><div className="signal" key={s.name}><span>{s.name.replaceAll('_',' ')}</span><b>{s.evidence}</b></div>)}{result.suggested_checks?.length>0&&<><h4>Следующие действия</h4><ul>{result.suggested_checks.map((s,i)=><li key={i}>{s}</li>)}</ul></>}<p className="limitations">{result.limitations}</p>{(result.evidence_node_ids||[undefined]).map((id,i)=><button key={id||i} onClick={()=>onEvidence(id)}><FileSearch size={16}/>VIEW EVIDENCE{result.evidence_node_ids?.length>1?` · ${id}`:''}</button>)}</article>
}
export default function AICopilot({node,result,messages,onExplain,onAsk,onEvidence,busy}){
 const [question,setQuestion]=useState('');
 const submit=e=>{e.preventDefault();if(question.trim()){onAsk(question.trim());setQuestion('');}};
 return <div className="copilot"><div className="copilot-intro"><Sparkles size={24}/><h3>Разобраться в связях</h3><p>Объяснения на основе рассчитанных показателей выбранного account.</p></div><button className="primary w-full" onClick={onExplain} disabled={busy||!node}>{busy?<LoaderCircle className="spin" size={16}/>:<Sparkles size={16}/>}Explain {node?.node_id||'account'}</button><AIResult result={result} onEvidence={onEvidence}/>{messages.map((m,i)=><div key={i}><div className="question-bubble">{m.question}</div><AIResult result={m.result} onEvidence={onEvidence}/></div>)}<div className="quick-questions">{['Какие сигналы самые сильные?','Куда уходят деньги после него?'].map(q=><button disabled={busy||!node} key={q} onClick={()=>onAsk(q)}>{q}</button>)}</div><form className="chat-form" onSubmit={submit}><input aria-label="Вопрос Copilot" value={question} maxLength={1000} onChange={e=>setQuestion(e.target.value)} placeholder="Спросите об этом account…" disabled={!node||busy}/><button className="primary" aria-label="Отправить вопрос" disabled={!node||busy||!question.trim()}><ArrowUp size={18}/></button></form><small className="muted">AI получает ограниченный контекст, не весь CSV.</small></div>
}
